"""Headless tests for the VTT core (parser / writer / project) and a smoke
test of the full UI using Qt's offscreen platform plugin.

The new undo/redo manager returns True/False instead of an index, so the
assertions below were updated to the current API while keeping every
original check (text edits, review flags, timestamps, BOM, autosave…).
"""
import os
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

SAMPLE = """WEBVTT
Kind: captions
Language: de

NOTE generated by test

1
00:00:00.000 --> 00:00:04.500 align:start position:0%
Willkommen zu dieser deutschen Geschichte.

2
00:00:04.500 --> 00:00:09.000
Heute erzählen wir eine Geschichte
mit Äpfeln, Öl und Straße.

3
00:01:23.500 --> 00:01:27.200
Mitten in einer großen Stat lag ein kleiner Zoo.

4
00:02:00,000 --> 00:02:04,000
Das ist ein kleiner
Elefant.
"""


def run_core_tests():
    from core.vtt_parser import read_vtt, parse_vtt_text, parse_timestamp, format_timestamp
    from core.vtt_writer import write_vtt, build_vtt_text
    from core.project import Project

    # timestamps
    assert abs(parse_timestamp("00:00:04.500") - 4.5) < 1e-9
    assert abs(parse_timestamp("00:01:23.500") - 83.5) < 1e-9
    assert abs(parse_timestamp("01:00:00.000") - 3600) < 1e-9
    assert abs(parse_timestamp("02:04,000") - 124.0) < 1e-9
    assert format_timestamp(83.5) == "00:01:23.500"

    doc = parse_vtt_text(SAMPLE)
    assert doc.cue_count == 4, doc.cue_count
    c2 = doc.cues[1]
    assert c2.start == 4.5 and c2.end == 9.0
    assert "erzählen" in c2.text and "Straße" in c2.text
    assert c2.identifier == "2"
    c3 = doc.cues[2]
    assert abs(c3.start - 83.5) < 1e-9 and abs(c3.end - 87.2) < 1e-9
    c4 = doc.cues[3]
    assert c4.text == "Das ist ein kleiner\nElefant.", repr(c4.text)
    assert doc.header_lines[0].startswith("WEBVTT")

    # round-trip without edits → identical content
    out = build_vtt_text(doc)
    assert out.replace("\r\n", "\n").strip() == SAMPLE.strip(), (out, SAMPLE)

    # edit only text of cue 2, timestamps untouched
    proj = Project()
    with tempfile.TemporaryDirectory() as td:
        p = os.path.join(td, "story.vtt")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(SAMPLE)
        proj.load_vtt(p)
        proj.set_cue_text(2, "Mitten in einer großen Stadt lag ein kleiner Zoo.")
        proj.mark_reviewed(0)
        assert proj.dirty
        proj.save()
        with open(p, encoding="utf-8") as fh:
            saved = fh.read()
        assert "Stadt lag" in saved
        assert "00:01:23.500 --> 00:01:27.200" in saved
        assert "align:start position:0%" in saved      # settings preserved
        assert "Kind: captions" in saved               # header preserved
        assert "Das ist ein kleiner\nElefant." in saved  # multiline preserved

        # undo / redo (last edit was mark_reviewed(0))
        idx = proj.undo()
        assert idx is True and not proj.cue(0).reviewed, idx
        idx = proj.undo()
        assert idx is True
        assert "Stat lag" in proj.cue(2).text
        proj.redo()
        assert "Stadt lag" in proj.cue(2).text

        # autosave never touches original
        proj.edits_since_autosave = 10
        ap = proj.do_autosave()
        assert ap and ap != p and os.path.isfile(ap)

        # search
        hits = proj.search("elefant")
        assert hits == [3], hits

        # BOM handling
        pb = os.path.join(td, "bom.vtt")
        with open(pb, "wb") as fh:
            fh.write(b"\xef\xbb\xbf" + SAMPLE.encode("utf-8"))
        d2 = read_vtt(pb)
        assert d2.had_bom and d2.cue_count == 4
        proj.document = d2
        proj.save(pb)
        with open(pb, "rb") as fh:
            assert fh.read().startswith(b"\xef\xbb\xbf")
    print("CORE TESTS OK")


def run_ui_smoke_test():
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    from PySide6.QtWidgets import QApplication
    app = QApplication.instance() or QApplication(sys.argv[:1])

    from ui.main_window import MainWindow
    win = MainWindow()
    win.show()

    with tempfile.TemporaryDirectory() as td:
        p = os.path.join(td, "story.vtt")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write(SAMPLE)

        win.open_vtt_dialog = lambda: None            # skip dialogs
        win.project.load_vtt(p)
        win.refresh_document()
        win.goto_cue(0)
        assert "Cue 1 / 4" in win.cue_counter_label.text()
        assert win.editor.toPlainText().startswith("Willkommen")
        assert "Not reviewed" in win.status_label.text()

        # Enter on cue index 2 ("Stat" → "Stadt") — displayed as "Cue 3 / 4"
        win.goto_cue(2)
        assert "Cue 3 / 4" in win.cue_counter_label.text()
        win.editor.setPlainText(
            "Mitten in einer großen Stadt lag ein kleiner Zoo.")
        win.commit_and_next()                          # what Enter does
        assert win.project.cue(2).reviewed
        assert "Stadt" in win.project.cue(2).text
        assert "Cue 4 / 4" in win.cue_counter_label.text()
        assert win.editor.toPlainText().startswith("Das ist ein kleiner")
        assert "\n" in win.editor.toPlainText()        # multi-line kept
        assert win.project.dirty

        # status label reflects reviewed
        win.goto_cue(2)
        assert "Reviewed" in win.status_label.text()

        # save as corrected copy
        outp = os.path.join(td, "story_corrected.vtt")
        win.project.save(outp)
        with open(outp, encoding="utf-8") as fh:
            data = fh.read()
        assert "Stadt lag" in data and "00:01:23.500" in data

        # cue list rows show ✓ marks
        texts = [win.cue_panel.list_widget.item(i).text()
                 for i in range(win.cue_panel.list_widget.count())]
        assert any(t.startswith("✓") for t in texts), texts

        # keyboard: Enter inside editor triggers commit+next via event filter
        from PySide6.QtCore import Qt as _Qt, QEvent
        from PySide6.QtGui import QKeyEvent
        n_before = win.current_index
        handled = win.eventFilter(win.editor, QKeyEvent(
            QEvent.Type.KeyPress, _Qt.Key.Key_Return,
            _Qt.KeyboardModifier.NoModifier))
        assert handled
        assert win.current_index == min(n_before + 1, win.project.cue_count - 1)

    print("UI SMOKE TEST OK")


if __name__ == "__main__":
    run_core_tests()
    run_ui_smoke_test()
    print("ALL TESTS PASSED")
